# Default application configuration that all configurations inherit from:
# https://github.com/causes/scss-lint/blob/master/config/default.yml

linters:
  Comment:
    enabled: false # False since style.dev.css should also contain heading comments

  DuplicateProperty:
    enabled: false

  Indentation:
    character: tab
    width: 1 # Set to one, as tabs are used, not spaces.

  LeadingZero:
    style: include_zero

  PropertySortOrder:
    enabled: false

  SelectorDepth:
    enabled: false

  SingleLinePerProperty:
    allow_single_line_rule_sets: false

  UrlQuotes:
    enabled: false
