# Grunt aliases
---
# Build dependencies
'build:dependencies:fonts':
  - 'bowercopy:fonts'
'build:dependencies:css':
  - 'clean:css'
  - 'bowercopy:css'
  - 'newer:copy:vendorcss'
'build:dependencies:js':
  - 'bowercopy:js'
'build:dependencies:php':
  - 'composer:install'
  - 'clean:hybridcore'
  - 'clean:vendor'
  - 'newer:copy:hybridcore'
  - 'newer:copy:flagshiplibrary'
  - 'newer:copy:themehookalliance'
# Build fonts from source to production
'build:fonts':
  - 'build:dependencies:fonts'
  - 'clean:fonts'
  - 'clean:icons'
  - 'newer:copy:fonts'
  - 'newer:imagemin:icons'
  - 'webfont'
# Build CSS from Scss to production
'build:css':
  - 'clean:style'
  - 'build:dependencies:css'
  - 'newer:sass'
  - 'newer:usebanner'
  - 'newer:autoprefixer'
  - 'newer:wpcss:css'
  - 'newer:cssjanus'
  - 'newer:cssmin'
  - 'newer:replace:style'
  - 'newer:copy:css'
  - 'newer:copy:editorstyle'
# Optimize images from source to production
'build:images':
  - 'newer:imagemin:images'
  - 'newer:copy:images'
  - 'newer:copy:screenshot'
# Build JavaScript from assets to production
'build:js':
  - 'clean:js'
  - 'build:dependencies:js'
  - 'newer:concat:js'
  - 'newer:uglify'
  - 'newer:jsvalidate:theme'
